from typing import Literal


LAST_INDEX = -1
FIRST_NODE_PORT = 10001
LOCAL_HOST = 'localhost'
POST_TRANSACTION_URL = f"http://{LOCAL_HOST}:5001/transaction"


class TRANSFER_OPERATIONS:
    TRANSFER = 'TRANSFER'
    STAKE = 'STAKE'
    EXCHANGE = 'EXCHANGE'


class MESSAGE_TYPES:
    DISCOVERY = 'DISCOVERY'
    TRANSACTION = 'TRANSACTION'
